# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='food_preferences',
        ),
        migrations.AddField(
            model_name='eventpreference',
            name='food_preference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.FoodPreference'),
            preserve_default=False,
        ),
    ]
