# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170625_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlocation',
            name='user_id',
            field=models.CharField(blank=True, help_text='Id of the Event creator', max_length=20, verbose_name='Event Location Creator'),
        ),
    ]
