# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20170709_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventshoppingitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='eventshoppingitem',
            name='bringer_id',
            field=models.CharField(blank=True, help_text='Id user who will bring the shopping item', max_length=20, verbose_name='Item Bringer'),
        ),
    ]
