# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170711_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventshoppingitem',
            name='amount',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
